export default function ReviewRecordsPanel({ position, onSave, onRead, onApply, onDismiss, pending, status, recordInfo, onUndo, canUndo, notesCount = 0 }) {
  return <section className="review-records no-print" aria-label="検討記録の保存と再開">
    <div className="review-records__bar"><div><strong>検討記録</strong><small>{recordInfo ? `${recordInfo.kind === 'example' ? '練習例' : '保存記録'}を表示中` : '条件と結果をファイルに残して再開'}{notesCount > 0 ? ` / 設備メモ ${notesCount}件` : ''}</small></div>
      <div className="review-records__actions"><button type="button" onClick={onSave} disabled={!position}>検討記録を保存</button><label className="review-records__file">記録ファイルを選ぶ<input type="file" accept=".json,application/json" onChange={onRead} aria-label="検討記録ファイルを選ぶ" /></label>{canUndo && <button type="button" onClick={onUndo}>開く前の記録に戻す</button>}</div>
    </div>
    <p className="review-records__notice">保存対象は候補地の条件・結果・メモです。PDF編集状態、結線アシストの機器設定、系統の全設備地図は含みません。</p>
    {recordInfo && <p className="review-records__notice">{recordInfo.kind === 'example' ? '仮条件の操作例です。計算結果や接続可否を示す実案件ではありません。' : `保存日時 ${new Date(recordInfo.savedAt).toLocaleString('ja-JP')} / 元のアプリ v${recordInfo.appVersion}。ファイル内の記録を復元しました。出典の再取得・原本との照合は行っていません。`}</p>}
    {status?.message && <p role={status.error ? 'alert' : 'status'} className="review-records__notice">{status.message}</p>}
    {pending && <div className="review-records__preview" role="region" aria-label="開く記録の確認"><h2>この記録を開きますか</h2><strong>{pending.candidate.name || pending.candidate.placeLabel || '候補地'}</strong><p>{pending.candidate.position.lat}, {pending.candidate.position.lon} / {new Date(pending.savedAt).toLocaleString('ja-JP')}</p><p>参考発電量 {pending.results.generation ? `${Math.round(pending.results.generation.annualKwh).toLocaleString('ja-JP')} kWh/年` : '未計算'} ／ 地平線 {pending.results.terrain ? '記録あり' : '未分析'} ／ 積雪 {pending.results.snowStation ? '記録あり' : '未取得'} ／ 設備メモ {pending.gridNotes.length}件</p><p>現在の候補地・条件・結果を置き換えます。開いた直後は「開く前の記録に戻す」で戻せます。残しておく場合は、先に現在の検討記録を保存してください。</p><div className="review-records__actions"><button type="button" className="primary-button" onClick={onApply}>この記録を開く</button><button type="button" onClick={onDismiss}>取り消す</button></div></div>}
  </section>
}
